## Task 1: Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [25]:
import numpy as np
import pandas as pd

In [26]:
np.random.seed(1)
df = np.random.rand(4,4)
df = pd.DataFrame(df)
df

          0         1         2         3
0  0.417022  0.720324  0.000114  0.302333
1  0.146756  0.092339  0.186260  0.345561
2  0.396767  0.538817  0.419195  0.685220
3  0.204452  0.878117  0.027388  0.670468

## Task 2: Rename the task - 1 'df dataframe column names to 'Random value 1', 'Random value 2", 'Random value 3' & 'Random value 4'

In [27]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3' , 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.417022        0.720324        0.000114        0.302333
1        0.146756        0.092339        0.186260        0.345561
2        0.396767        0.538817        0.419195        0.685220
3        0.204452        0.878117        0.027388        0.670468

## Task 3: Find the descriptive statistics of the 'df dataframe.

In [28]:
df. describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.291249        0.557399        0.158239        0.500895
std          0.135849        0.339623        0.192361        0.205172
min          0.146756        0.092339        0.000114        0.302333
25%          0.190028        0.427197        0.020569        0.334754
50%          0.300610        0.629571        0.106824        0.508014
75%          0.401831        0.759773        0.244494        0.674156
max          0.417022        0.878117        0.419195        0.685220

## Task 4: Check for the null values in 'df and find the data type of the columns.

In [29]:
df.isnull().values.any()

False

In [30]:
df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [31]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [32]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [34]:
#For Data Type
dt = df.dtypes
print(dt)

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

## Task 5: Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [44]:
df.loc[:,['Random value 2','Random value 3']] #using loc method

   Random value 2  Random value 3
0        0.720324        0.000114
1        0.092339        0.186260
2        0.538817        0.419195
3        0.878117        0.027388

In [45]:
df.iloc[:,1:3] # using iloc method

   Random value 2  Random value 3
0        0.720324        0.000114
1        0.092339        0.186260
2        0.538817        0.419195
3        0.878117        0.027388